name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug SSH Private Key FARHAD Length
        run: |
          echo "Private Key Length: ${#SSH_PRIVATE_FARHADALI558}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_FARHADALI558 }}

      - name: Debug SSH Private Key BROS Length
        run: |
          echo "Private Key Length: ${#SSH_PRIVATE_ABBASIBROS}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_ABBASIBROS }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_FARHADALI558 }}


#      - name: Test SSH connection to GitHub
#        run: |
#          ssh -T git@github.com

      - name: SSH into VPS and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@91.99.121.54 << 'EOF'
            cd ~/agent-stack &&
            git pull origin main &&
            docker compose down &&
            docker compose up -d
          EOF
